"""Abstract repository interfaces for Calendar, Expense, Note, Countdown aggregates."""

from abc import ABC, abstractmethod
from uuid import UUID
from app.domain.entities import CalendarEntity, ExpenseEntity, NoteEntity, CountdownEntity


class CalendarRepository(ABC):
    @abstractmethod
    async def list_by_user(self, user_id: UUID) -> list[CalendarEntity]: ...
    @abstractmethod
    async def get_by_id(self, event_id: UUID, user_id: UUID) -> CalendarEntity | None: ...
    @abstractmethod
    async def add(self, entity: CalendarEntity) -> CalendarEntity: ...
    @abstractmethod
    async def update(self, entity: CalendarEntity) -> CalendarEntity: ...
    @abstractmethod
    async def delete(self, event_id: UUID, user_id: UUID) -> bool: ...


class ExpenseRepository(ABC):
    @abstractmethod
    async def list_by_user(self, user_id: UUID) -> list[ExpenseEntity]: ...
    @abstractmethod
    async def get_by_id(self, expense_id: UUID, user_id: UUID) -> ExpenseEntity | None: ...
    @abstractmethod
    async def add(self, entity: ExpenseEntity) -> ExpenseEntity: ...
    @abstractmethod
    async def update(self, entity: ExpenseEntity) -> ExpenseEntity: ...
    @abstractmethod
    async def delete(self, expense_id: UUID, user_id: UUID) -> bool: ...
    @abstractmethod
    async def get_stats(self, user_id: UUID, since: str, until: str) -> dict: ...
    @abstractmethod
    async def get_weekly_insights(self, user_id: UUID) -> dict: ...


class NoteRepository(ABC):
    @abstractmethod
    async def list_by_user(self, user_id: UUID, note_type: str | None = None) -> list[NoteEntity]: ...
    @abstractmethod
    async def get_by_id(self, note_id: UUID, user_id: UUID) -> NoteEntity | None: ...
    @abstractmethod
    async def add(self, entity: NoteEntity) -> NoteEntity: ...
    @abstractmethod
    async def update(self, entity: NoteEntity) -> NoteEntity: ...
    @abstractmethod
    async def delete(self, note_id: UUID, user_id: UUID) -> bool: ...


class CountdownRepository(ABC):
    @abstractmethod
    async def list_by_user(self, user_id: UUID) -> list[CountdownEntity]: ...
    @abstractmethod
    async def add(self, entity: CountdownEntity) -> CountdownEntity: ...
    @abstractmethod
    async def delete(self, countdown_id: UUID, user_id: UUID) -> bool: ...
