"""add_conv_memories_table

Revision ID: 1a2b3c4d5e6f
Revises: f121352eeb65
Create Date: 2026-06-06 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2b3c4d5e6f'
down_revision: Union[str, None] = '535abfe1fabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conv_memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conv_id', sa.Uuid(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False, server_default=''),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conv_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conv_memories_user_id'), 'conv_memories', ['user_id'], unique=False)
    op.create_index(op.f('ix_conv_memories_conv_id'), 'conv_memories', ['conv_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conv_memories_user_id'), table_name='conv_memories')
    op.drop_index(op.f('ix_conv_memories_conv_id'), table_name='conv_memories')
    op.drop_table('conv_memories')
    # ### end Alembic commands ###