"""add_study_children_table

Revision ID: 595677bb60ea
Revises: 1a2b3c4d5e6f
Create Date: 2026-06-16 20:12:04.038928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '595677bb60ea'
down_revision: Union[str, None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_children',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_children_user_id'), 'study_children', ['user_id'], unique=False)
    op.alter_column('knowledge_bases', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('knowledge_chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_kcm_kb_user', table_name='knowledge_chat_messages')
    op.create_index(op.f('ix_knowledge_chat_messages_kb_id'), 'knowledge_chat_messages', ['kb_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chat_messages_user_id'), 'knowledge_chat_messages', ['user_id'], unique=False)
    op.add_column('study_records', sa.Column('child_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_study_records_child_id'), 'study_records', ['child_id'], unique=False)
    op.create_foreign_key(None, 'study_records', 'study_children', ['child_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_records', type_='foreignkey')
    op.drop_index(op.f('ix_study_records_child_id'), table_name='study_records')
    op.drop_column('study_records', 'child_id')
    op.drop_index(op.f('ix_knowledge_chat_messages_user_id'), table_name='knowledge_chat_messages')
    op.drop_index(op.f('ix_knowledge_chat_messages_kb_id'), table_name='knowledge_chat_messages')
    op.create_index('idx_kcm_kb_user', 'knowledge_chat_messages', ['kb_id', 'user_id', 'created_at'], unique=False)
    op.alter_column('knowledge_chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_bases', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_study_children_user_id'), table_name='study_children')
    op.drop_table('study_children')
    # ### end Alembic commands ###
