"""add_embedding_to_user_memories

Revision ID: 732c5bc62415
Revises: 595677bb60ea
Create Date: 2026-06-16 21:49:39.144758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '732c5bc62415'
down_revision: Union[str, None] = '595677bb60ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_memories', sa.Column('embedding', postgresql.ARRAY(sa.Float(), dimensions=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_memories', 'embedding')
    # ### end Alembic commands ###
