"""add_converted_files_table

Revision ID: bb45db1b9093
Revises: 5c8ef1803b70
Create Date: 2026-05-31 10:11:46.347360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb45db1b9093'
down_revision: Union[str, None] = '5c8ef1803b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('converted_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=False),
    sa.Column('target_name', sa.String(length=300), nullable=False),
    sa.Column('object_name', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_converted_files_user_id'), 'converted_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_converted_files_user_id'), table_name='converted_files')
    op.drop_table('converted_files')
    # ### end Alembic commands ###
