"""add_lesson_contents_table

Revision ID: c4adae6ad74a
Revises: 4b49dedf89a4
Create Date: 2026-07-02 20:23:32.880557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4adae6ad74a'
down_revision: Union[str, None] = '4b49dedf89a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_contents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('lesson_name', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('key_points', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_contents_lesson_name'), 'lesson_contents', ['lesson_name'], unique=False)
    op.create_index(op.f('ix_lesson_contents_subject'), 'lesson_contents', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_contents_subject'), table_name='lesson_contents')
    op.drop_index(op.f('ix_lesson_contents_lesson_name'), table_name='lesson_contents')
    op.drop_table('lesson_contents')
    # ### end Alembic commands ###
