"""add_user_emotion_states

Revision ID: e12ca4f16d7c
Revises: ac17d4b265f1
Create Date: 2026-05-31 11:32:17.509468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e12ca4f16d7c'
down_revision: Union[str, None] = 'ac17d4b265f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_emotion_states',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('current_emotion', sa.String(length=20), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_emotion_states')
    # ### end Alembic commands ###
